[build]
  # No base needed - command runs from root
  # Install root dependencies first, then build the web app
  command = "npm install && npm run build --prefix assemblage-web"
  publish = "assemblage-web/dist" # Path relative to root
  functions = "netlify/functions" # Path relative to root

[build.environment]
  NODE_VERSION = "18"

[dev]
  command = "cd assemblage-web && npm run dev"
  port = 8888
  functions = "netlify/functions"
  targetPort = 5175 