[build]
  base = "assemblage-web" # Set base directory for build context
  command = "npm ci && npm run build" # Install & build within assemblage-web
  publish = "dist" # Publish the dist folder from assemblage-web
  functions = "../netlify/functions" # Path to functions relative to base

[build.environment]
  NODE_VERSION = "18"
  # Explicitly set NODE_ENV for build
  NODE_ENV = "production"

[dev]
  command = "cd assemblage-web && npm run dev"
  port = 8888
  functions = "netlify/functions"
  targetPort = 5175 