[build]
  command = "cd assemblage-web && npm install && npm run build"
  publish = "assemblage-web/dist"
  functions = "netlify/functions"
 
[dev]
  command = "cd assemblage-web && npm run dev"
  port = 8888
  functions = "netlify/functions"
  targetPort = 5175 