[build]
  base = "assemblage-web"
  command = "npm install && cd assemblage-web && npm ci && npm run build" # Install root deps first, then build web
  publish = "dist"
  functions = "../netlify/functions"

[build.environment]
  NODE_VERSION = "18"

[dev]
  command = "cd assemblage-web && npm run dev"
  port = 8888
  functions = "netlify/functions"
  targetPort = 5175 