[build]
  base = "assemblage-web"
  command = "npm ci && npm run build" # Use npm ci for cleaner installs
  publish = "dist"
  functions = "../netlify/functions"

[build.environment]
  NODE_VERSION = "18"
  # Explicitly set NODE_ENV for build
  NODE_ENV = "production"

[dev]
  command = "cd assemblage-web && npm run dev"
  port = 8888
  functions = "netlify/functions"
  targetPort = 5175 