[build]
  # No base needed - command runs from root
  # 1. Install root dependencies (for functions)
  # 2. cd into assemblage-web, install its dependencies, then build it
  command = "npm install && (cd assemblage-web && npm install && npm run build)"
  publish = "assemblage-web/dist" # Path relative to root
  functions = "netlify/functions" # Path relative to root

[build.environment]
  NODE_VERSION = "18"

[dev]
  command = "cd assemblage-web && npm run dev"
  port = 8888
  functions = "netlify/functions"
  targetPort = 5175 