[build]
  # No base needed - command runs from root
  # 1. Install root dependencies (for functions)
  # 2. Install assemblage-web dependencies (for its build process)
  # 3. Build assemblage-web
  command = "npm install && npm install --prefix assemblage-web && npm run build --prefix assemblage-web"
  publish = "assemblage-web/dist" # Path relative to root
  functions = "netlify/functions" # Path relative to root

[build.environment]
  NODE_VERSION = "18"

[dev]
  command = "cd assemblage-web && npm run dev"
  port = 8888
  functions = "netlify/functions"
  targetPort = 5175 