[build]
  base = "assemblage-web"
  command = "cd .. && npm ci && cd assemblage-web && npm ci && npm run build" # Install root deps, then web deps, then build web
  publish = "dist"
  functions = "../netlify/functions"

[build.environment]
  NODE_VERSION = "18"

[dev]
  command = "cd assemblage-web && npm run dev"
  port = 8888
  functions = "netlify/functions"
  targetPort = 5175

# Increase timeout for the metadata generation function
[functions."generate-image-metadata"]
  timeout = 60 # seconds 